name: TryHackMe Update Badge
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repos tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "zhaambo"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
